name: "Announcement (maintainers)"
description: Maintainer notes, releases, deprecations.
labels: [announcement]
title: "[Announce] <topic>"
body:
  - type: textarea
    id: note
    attributes: { label: Note }
    validations: { required: true }
