# Discussion template for announcements
title: "[Announce] <topic>"
labels: [announcement]
body:
  - type: markdown
    attributes:
      value: |
        ## Announcement

  - type: textarea
    id: note
    attributes:
      label: Notes
      description: What is new, changed, or deprecated.
      placeholder: Brief summary…
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Details
      description: Optional longer description / links / migration notes.
